name: 'Deploy Node.js to Sakura AppRun'
description: 'Build and deploy Node.js applications to Sakura AppRun'
author: 'Toshihiro Shimizu'
branding:
  icon: 'cloud'
  color: 'purple'

inputs:
  dockerfile-url:
    description: 'URL to download Dockerfile from'
    required: false
    default: 'https://raw.githubusercontent.com/meso/sakura-apprun-action/main/Dockerfile.node'
  sakura-api-key:
    description: 'Sakura Cloud API Key'
    required: true
  sakura-api-secret:
    description: 'Sakura Cloud API Secret'
    required: true
  container-registry:
    description: 'Container registry URL (e.g., myregistry.sakuracr.jp)'
    required: true
  container-registry-user:
    description: 'Container registry username'
    required: true
  container-registry-password:
    description: 'Container registry password'
    required: true
  app-name:
    description: 'Application name (defaults to repository name)'
    required: false
    default: ''
  port:
    description: 'Application port'
    required: false
    default: '3000'
  max-cpu:
    description: 'Maximum CPU (e.g., "1", "0.5")'
    required: false
    default: '0.5'
  max-memory:
    description: 'Maximum memory (e.g., "512Mi", "1Gi")'
    required: false
    default: '256Mi'
  timeout-seconds:
    description: 'Request timeout in seconds'
    required: false
    default: '300'
  sakura-object-storage-bucket:
    description: 'Sakura Object Storage bucket name for SQLite backup (enables Litestream when all S3 credentials are provided)'
    required: false
    default: ''
  sakura-object-storage-access-key:
    description: 'Sakura Object Storage access key'
    required: false
    default: ''
  sakura-object-storage-secret-key:
    description: 'Sakura Object Storage secret key'
    required: false
    default: ''
  sqlite-db-path:
    description: 'Path to SQLite database file (required when using Litestream backup)'
    required: false
    default: ''
  litestream-replicate-interval:
    description: 'Litestream replication interval (e.g., "1s", "10s")'
    required: false
    default: '10s'

outputs:
  public-url:
    description: 'The public URL of the deployed application'
    value: ${{ steps.deploy.outputs.public-url }}
  app-id:
    description: 'The AppRun application ID'
    value: ${{ steps.deploy.outputs.app-id }}

runs:
  using: 'composite'
  steps:
    - name: Determine Dockerfile to use
      id: dockerfile
      shell: bash
      run: |
        # Check if Litestream should be enabled
        if [ -n "${{ inputs.sakura-object-storage-bucket }}" ] && \
           [ -n "${{ inputs.sakura-object-storage-access-key }}" ] && \
           [ -n "${{ inputs.sakura-object-storage-secret-key }}" ] && \
           [ -n "${{ inputs.sqlite-db-path }}" ]; then
          echo "Litestream backup enabled"
          echo "use_litestream=true" >> $GITHUB_OUTPUT
          DOCKERFILE_URL="${{ inputs.dockerfile-url || 'https://raw.githubusercontent.com/meso/sakura-apprun-action/main/Dockerfile.node-litestream' }}"
        else
          echo "Standard deployment (no Litestream)"
          echo "use_litestream=false" >> $GITHUB_OUTPUT
          DOCKERFILE_URL="${{ inputs.dockerfile-url || 'https://raw.githubusercontent.com/meso/sakura-apprun-action/main/Dockerfile.node' }}"
        fi
        
        # Download Dockerfile if not exists
        if [ ! -f Dockerfile ]; then
          echo "Downloading Dockerfile from $DOCKERFILE_URL"
          curl -fsSL -o Dockerfile "$DOCKERFILE_URL"
        fi
        
    - name: Set app name
      id: app-name
      shell: bash
      run: |
        APP_NAME="${{ inputs.app-name }}"
        if [ -z "$APP_NAME" ]; then
          APP_NAME="${{ github.event.repository.name }}"
        fi
        echo "name=${APP_NAME}" >> $GITHUB_OUTPUT
        
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.container-registry }}
        username: ${{ inputs.container-registry-user }}
        password: ${{ inputs.container-registry-password }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ inputs.container-registry }}/${{ steps.app-name.outputs.name }}:latest
          ${{ inputs.container-registry }}/${{ steps.app-name.outputs.name }}:${{ github.sha }}
        provenance: false
        
    - name: Deploy to AppRun
      id: deploy
      shell: bash
      run: |
        # Create auth header
        AUTH=$(echo -n "${{ inputs.sakura-api-key }}:${{ inputs.sakura-api-secret }}" | base64 | tr -d '\n')
        
        # Build environment variables array
        ENV_VARS="[]"
        if [ -n "${{ inputs.sakura-object-storage-bucket }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"name": "SAKURA_OBJECT_STORAGE_BUCKET", "value": "${{ inputs.sakura-object-storage-bucket }}"}]')
        fi
        if [ -n "${{ inputs.sakura-object-storage-access-key }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"name": "SAKURA_OBJECT_STORAGE_ACCESS_KEY", "value": "${{ inputs.sakura-object-storage-access-key }}"}]')
        fi
        if [ -n "${{ inputs.sakura-object-storage-secret-key }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"name": "SAKURA_OBJECT_STORAGE_SECRET_KEY", "value": "${{ inputs.sakura-object-storage-secret-key }}"}]')
        fi
        if [ -n "${{ inputs.sqlite-db-path }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"name": "SQLITE_DB_PATH", "value": "${{ inputs.sqlite-db-path }}"}]')
        fi
        if [ -n "${{ inputs.litestream-replicate-interval }}" ]; then
          ENV_VARS=$(echo "$ENV_VARS" | jq '. + [{"name": "LITESTREAM_REPLICATE_INTERVAL", "value": "${{ inputs.litestream-replicate-interval }}"}]')
        fi
        
        # Create request body with jq
        REQUEST_BODY=$(jq -n \
          --arg name "${{ steps.app-name.outputs.name }}" \
          --arg timeout "${{ inputs.timeout-seconds }}" \
          --arg port "${{ inputs.port }}" \
          --arg component_name "${{ steps.app-name.outputs.name }}:${{ github.sha }}" \
          --arg max_cpu "${{ inputs.max-cpu }}" \
          --arg max_memory "${{ inputs.max-memory }}" \
          --arg image "${{ inputs.container-registry }}/${{ steps.app-name.outputs.name }}:${{ github.sha }}" \
          --arg server "${{ inputs.container-registry }}" \
          --arg username "${{ inputs.container-registry-user }}" \
          --arg password "${{ inputs.container-registry-password }}" \
          --argjson env_vars "$ENV_VARS" \
          '{
            "name": $name,
            "timeout_seconds": ($timeout | tonumber),
            "port": ($port | tonumber),
            "min_scale": 0,
            "max_scale": 1,
            "components": [
              {
                "name": $component_name,
                "max_cpu": $max_cpu,
                "max_memory": $max_memory,
                "deploy_source": {
                  "container_registry": {
                    "image": $image,
                    "server": $server,
                    "username": $username,
                    "password": $password
                  }
                },
                "env": $env_vars
              }
            ]
          }')
        
        # Check if application already exists
        APP_NAME="${{ steps.app-name.outputs.name }}"
        EXISTING_APPS=$(curl -s -X GET \
          -H "Authorization: Basic ${AUTH}" \
          -H "Content-Type: application/json" \
          https://secure.sakura.ad.jp/cloud/api/apprun/1.0/apprun/api/applications)
        
        # Extract app ID if exists
        APP_ID=$(echo "$EXISTING_APPS" | grep -o "\"id\":\"[^\"]*\".*\"name\":\"$APP_NAME\"" | grep -o "\"id\":\"[^\"]*\"" | sed 's/"id":"//' | sed 's/"//')
        
        if [ -n "$APP_ID" ]; then
          echo "Updating existing application: $APP_ID"
          # Update existing application
          RESPONSE=$(curl -s -X PATCH \
            -H "Authorization: Basic ${AUTH}" \
            -H "Content-Type: application/json" \
            -d "${REQUEST_BODY}" \
            https://secure.sakura.ad.jp/cloud/api/apprun/1.0/apprun/api/applications/${APP_ID})
        else
          echo "Creating new application"
          # Create new application
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Basic ${AUTH}" \
            -H "Content-Type: application/json" \
            -d "${REQUEST_BODY}" \
            https://secure.sakura.ad.jp/cloud/api/apprun/1.0/apprun/api/applications)
        fi
        
        # Extract values
        echo "Debug: API Response received"
        echo "Full response:"
        echo "$RESPONSE"
        echo "--- End of response ---"
        
        PUBLIC_URL=$(echo "$RESPONSE" | grep -o '"public_url":"[^"]*' | sed 's/"public_url":"//') || true
        APP_ID=$(echo "$RESPONSE" | grep -o '"id":"[^"]*' | sed 's/"id":"//') || true
        
        echo "Debug: Extracted PUBLIC_URL='$PUBLIC_URL'"
        echo "Debug: Extracted APP_ID='$APP_ID'"
        
        # Set outputs
        echo "public-url=${PUBLIC_URL}" >> $GITHUB_OUTPUT
        echo "app-id=${APP_ID}" >> $GITHUB_OUTPUT
        
        if [ -n "$PUBLIC_URL" ]; then
          echo "🚀 Successfully deployed to: $PUBLIC_URL"
        else
          echo "❌ Deployment failed"
          echo "$RESPONSE"
          exit 1
        fi